# .github/workflows/whatsapp-redirect-chatbot.yml
name: WhatsApp Redirect Chatbot Maintenance

on:
  schedule:
    - cron: '0 5 * * 1'
  workflow_dispatch:

jobs:
  maintain-and-validate:
    name: Weekly File Check & Update
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node Environment
        continue-on-error: true
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Ensure Directory Structure
        continue-on-error: true
        run: mkdir -p public src .github/workflows

      - name: Generate index.html
        continue-on-error: true
        run: |
          cat <<"EOF" > public/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>WhatsApp Redirect Chatbot</title>
          </head>
          <body>
            <h1>Choose a Department</h1>
            <button onclick="redirectToWhatsApp('sales')">Sales</button>
            <button onclick="redirectToWhatsApp('support')">Support</button>
            <script src="../src/redirect.js"></script>
          </body>
          </html>
          EOF

      - name: Generate config.js
        continue-on-error: true
        run: |
          cat <<"EOF" > src/config.js
          export const departments = {
            sales: { number: process.env.SALES_NUMBER || 'default_sales_number', message: 'Hi Sales Team, I need pricing info' },
            support: { number: process.env.SUPPORT_NUMBER || 'default_support_number', message: 'Hello, I need technical assistance' }
          };
          EOF

      - name: Generate redirect.js
        continue-on-error: true
        run: |
          cat <<"EOF" > src/redirect.js
          import { departments } from './config.js';

          window.redirectToWhatsApp = function (departmentKey) {
            const dept = departments[departmentKey];
            if (!dept) return alert('Invalid department');
            const url = `https://wa.me/${dept.number}?text=${encodeURIComponent(dept.message)}`;
            window.open(url, '_blank');
          };
          EOF

      - name: Generate .env
        continue-on-error: true
        run: |
          cat <<"EOF" > .env
          SALES_NUMBER=default_sales_number
          SUPPORT_NUMBER=default_support_number
          EOF

      - name: Generate package.json
        continue-on-error: true
        run: |
          cat <<"EOF" > package.json
          {
            "name": "whatsapp-redirect-chatbot",
            "version": "1.0.0",
            "description": "A static webpage to redirect users to appropriate WhatsApp numbers using buttons.",
            "main": "server.js",
            "scripts": {
              "start": "node server.js",
              "test": "echo \"Error: no test specified\" && exit 1"
            },
            "author": "Skunkworks",
            "license": "MIT",
            "dependencies": {
              "express": "^4.18.2"
            }
          }
          EOF

      - name: Generate server.js
        continue-on-error: true
        run: |
          cat <<"EOF" > server.js
          const express = require('express');
          const path = require('path');
          const app = express();
          const PORT = process.env.PORT || 3000;

          app.use(express.static(path.join(__dirname, 'public')));

          app.get('/', (req, res) => {
            res.sendFile(path.join(__dirname, 'public', 'index.html'));
          });

          app.listen(PORT, () => {
            console.log(`Server is running on http://localhost:${PORT}`);
          });
          EOF

      - name: Generate README.md
        continue-on-error: true
        run: |
          cat <<"EOF" > README.md
          # WhatsApp Redirect Chatbot

          A static webpage to redirect users to appropriate WhatsApp numbers using buttons.

          ## Usage
          Open public/index.html or deploy via GitHub Pages.
          EOF

                - name: Generate .gitignore
                  continue-on-error: true
                  run: echo -e "node_modules/\ndist/\n.env" > .gitignore

                - name: Generate LICENSE
                  continue-on-error: true
                  run: |
                    cat <<"EOF" > LICENSE
          MIT License

          Permission is hereby granted, free of charge, to any person obtaining a copy
          of this software and associated documentation files (the "Software"), to deal
          in the Software without restriction, including without limitation the rights
          to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
          copies of the Software, and to permit persons to whom the Software is
          furnished to do so, subject to the following conditions:

          THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
          EOF

      - name: Run Prettier (Code Formatting)
        continue-on-error: true
        run: |
          npm install --global prettier || echo 'Prettier installation failed'
          prettier --write "**/*.{js,jsx,json,md,html,css,yml,yaml,ts,tsx}" || echo 'Prettier failed, continuing anyway'

      - name: Deploy to GitHub Pages
        continue-on-error: true
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Git Commit & Push Changes
        continue-on-error: true
        run: |
          git config --global user.name 'skunkworks-bot'
          git config --global user.email 'automation@skunkworks.africa'
          git add .
          git commit -m "🚀 Weekly auto-maintenance and sync" || echo "No changes to commit"
          git push origin HEAD || echo "Push skipped or failed"

      - name: Print Workflow Completion Summary
        if: always()
        run: echo "✅ Maintenance workflow completed (with or without warnings)."

      - name: Handle Failure Notifications
        if: failure()
        run: |
          echo "❌ Maintenance encountered a failure. Review logs above for diagnostics."
          exit 1

      - name: Discord Notification (on success)
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"username": "GitHub Bot", "content": "✅ Workflow succeeded. Site deployed and code updated: https://github.com/burnt-exe/whatsapp-redirect-chatbot/actions"}' \
               ${{ secrets.DISCORD_WEBHOOK }}
      
      - name: Force Add All Files
        run: |
          git config --global user.name 'skunkworks-bot'
          git config --global user.email 'automation@skunkworks.africa'
          git add -A
          git commit -am "🔧 Initialize generated files" || echo "No changes to commit"
          git push origin HEAD || echo "Push skipped or failed"
