# .github/workflows/whatsapp-redirect-chatbot.yml
name: WhatsApp Redirect Chatbot Maintenance

on:
  schedule:
    - cron: '0 5 * * 1'  # Every Monday at 05:00 UTC
  workflow_dispatch:

jobs:
  maintain-and-validate:
    name: Weekly File Check & Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node Environment
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Ensure Directory Structure
        run: |
          mkdir -p public src .github/workflows

      - name: Generate Core Project Files
        run: | 
          cat <<"EOF_HTML" > public/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>WhatsApp Redirect Chatbot</title>
          </head>
          <body>
            <h1>Choose a Department</h1>
            <button onclick="redirectToWhatsApp('sales')">Sales</button>
            <button onclick="redirectToWhatsApp('support')">Support</button>
            <script src="../src/redirect.js"></script>
          </body>
          </html>
          EOF_HTML
          
          cat <<"EOF_JS" > src/config.js
            export const departments = {
            sales: { number: '27830000000', message: 'Hi Sales Team, I need pricing info' },
            support: { number: '27831111111', message: 'Hello, I need technical assistance' }
          };
          EOF_JS
          
          cat <<"EOF_JS2" > src/redirect.js
          import { departments } from './config.js';
          
          window.redirectToWhatsApp = function (departmentKey) {
            const dept = departments[departmentKey];
            if (!dept) return alert('Invalid department');
            const url = `https://wa.me/${dept.number}?text=${encodeURIComponent(dept.message)}`;
            window.open(url, '_blank');
          };
          EOF_JS2
          
          cat <<"EOF_MD" > README.md
          # WhatsApp Redirect Chatbot
          
          A static webpage to redirect users to appropriate WhatsApp numbers using buttons.
          
          ## Usage
          Open public/index.html or deploy via GitHub Pages.
          EOF_MD
          
          echo "node_modules/
          dist/
          .env" > .gitignore
          
          cat <<"EOF_LIC" > LICENSE
          MIT License
          
          Permission is hereby granted, free of charge, to any person obtaining a copy
          of this software and associated documentation files (the "Software"), to deal
          in the Software without restriction, including without limitation the rights
          to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
          copies of the Software, and to permit persons to whom the Software is
          furnished to do so, subject to the following conditions:
          
          THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
          EOF_LIC

      - name: Run Prettier (Code Formatting)
        run: |
          npm install --global prettier || echo 'Prettier installation failed'
          prettier --write "**/*.{js,jsx,json,md,html,css,yml,yaml,ts,tsx}" || echo 'Prettier failed, continuing anyway'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Git Commit & Push Changes
        run: |
          git config --global user.name 'skunkworks-bot'
          git config --global user.email 'automation@skunkworks.africa'
          git add .
          git commit -m "🚀 Weekly auto-maintenance and sync" || echo "No changes to commit"
          git push origin HEAD || echo "Push skipped or failed"

      - name: Print Workflow Completion Summary
        if: always()
        run: echo "✅ Maintenance workflow completed successfully."

      - name: Handle Failure Notifications
        if: failure()
        run: |
          echo "❌ Maintenance encountered a failure. Review logs above for diagnostics."
          exit 1

      - name: Notify via Email on Success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "✅ WhatsApp Redirect Chatbot - Maintenance Success"
          to: raydo@skunkworks.africa
          from: GitHub Actions Bot <automation@skunkworks.africa>
          body: |
            Weekly maintenance of the WhatsApp Redirect Chatbot completed successfully.
            ✅ Repository synced and validated.
            📁 Files updated and formatted.
            🌐 Deployed to GitHub Pages.
            View it here: https://github.com/burnt-exe/whatsapp-redirect-chatbot/actions

      - name: Notify via Email on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "❌ WhatsApp Redirect Chatbot - Maintenance Failed"
          to: raydo@skunkworks.africa
          from: GitHub Actions Bot <automation@skunkworks.africa>
          body: |
            The scheduled maintenance workflow failed.
            ❌ Errors were encountered during execution.
            Please review logs: https://github.com/burnt-exe/whatsapp-redirect-chatbot/actions

      - name: Slack Notification (on failure)
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: '#FF0000'
          SLACK_TITLE: '❌ WhatsApp Chatbot Maintenance Failed'
          SLACK_MESSAGE: 'Please check the logs at https://github.com/burnt-exe/whatsapp-redirect-chatbot/actions'

      - name: Slack Notification (on success)
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: '#00FF00'
          SLACK_TITLE: '✅ WhatsApp Chatbot Maintenance Successful'
          SLACK_MESSAGE: 'Site deployed and code updated: https://github.com/burnt-exe/whatsapp-redirect-chatbot/actions'
